### ISSUE TITLE
Diagonal separations and color gradients in progress bars

### ISSUE THREAD

**Issue by jacomyal** [kristopolous/BOOTSTRA.386#11]
Examples [here](https://kristopolous.github.io/BOOTSTRA.386/components.html#progress).

**Edit:**
Forgot to specify: the problem is that the progress bars don't look that much 80's with gradients and diagonal separation.

**Comment by kristopolous** [comment]
closing this out via JWZ's CADT: https://www.jwz.org/doc/cadt.html ... on to BS 4.
