### ISSUE TITLE
Stylesheet is not set for the example page

### ISSUE THREAD

**Issue by ullenboom** [kristopolous/BOOTSTRA.386#137]
![image](https://github.com/kristopolous/BOOTSTRA.386/assets/5071169/8f92c481-5d6c-4775-a35e-fa0d7531dd5a)

**Comment by kristopolous** [comment]
thanks, i'm aware. I'm working on it

**Comment by kristopolous** [comment]
alright fixed. now I just have to make it not look so ugly
