### ISSUE TITLE
[feature request] add rectangle jumping cursor

### ISSUE THREAD

**Issue by Levsha128** [kristopolous/BOOTSTRA.386#21]
some demo-code for demonstration of idea:

``` javascript
w = 10;
h = 20;
b = document.getElementsByTagName('body')[0];
b.style.cursor = 'none'

d = document.createElement('div');
d.id = 'nicecursor';
b.appendChild(d);
a = document.getElementById('nicecursor');
a.style.position = 'absolute';
a.style.top = '10px';
a.style.left = '10px';
a.style.width = w+'px';
a.style.height = h+'px';
a.style.backgroundColor = 'white';
a.style.pointerEvents = 'none';

b.onmousemove = function(e){
    a.style.left = e.pageX - e.pageX % w   +'px';
    a.style.top = e.pageY - e.pageY % h +'px';

}
```

**Comment by javatlacati** [comment]
What about something like that using mix-blend mode:

https://jsfiddle.net/javatlacati/5jvnxpkb/

**Comment by kristopolous** [comment]
> What about something like that using mix-blend mode:
> 
> https://jsfiddle.net/javatlacati/5jvnxpkb/

oh interesting ... you know I should probably get a feature set for this thing sometime. This will solve another problem of mine, which is the true dos shadow. Look here: https://github.com/kristopolous/BOOTSTRA.386/wiki/Gallery ... many programs cleverly simulated a darken effect.  We need to somehow ignore the true color darken we have now and re-simulate their darken.

**Comment by kristopolous** [comment]
#86 covers it ... thanks for the code ... I used most of it.
