### ISSUE TITLE
Override scrolling behavior to constrain location to character grid.

### ISSUE THREAD

**Issue by JTxt** [kristopolous/BOOTSTRA.386#25]
Observations while playing with edit.exe in dosbox:
- Pageup/down scrolls by one page instantly.
-  Blinking underline cursor shows and controls active position in document area. (not menu, but does show up on active button.)
  - Moved by mouse with a click or arrow keys. (if on a menu, it disapears.)
  - If at the edge, arrowkeys scroll by one character. if at the bottom, downarrow key it scrolls by one line, 
- If a navigation key is held down, it moves by one page/character, then after a brief pause, (400 ms?) it repeats with a very short pause.

Now the blinking underline may be too much for now.  (edit: and it may be better to have a LYNX style navigation for keyboard, so you move from link to link?  but more complicated?)

At least, scrolling can be constrained to the character grid, but may have trouble in some browsers.

This project demonstrates disabling and controlling scrolling some:
http://naeka.github.io/jquery-scrollbar/
window.scrollTo(500,0);
http://help.dottoro.com/ljcjcwuo.php

Edit: changed title from: "Scroll behaviour: Not constrained to character grid, Not properly keyboard/swipe responsive." to "Override scrolling behavior to constrain location to character grid."

**Comment by kristopolous** [comment]
really this should be implemented outside the project ... it may already exist elsewhere and can just be integrated, you know, like a library

**Comment by kristopolous** [comment]
this is covered in #86 ... finally.
