### ISSUE TITLE
Ideas...

### ISSUE THREAD

**Issue by IngwiePhoenix** [kristopolous/BOOTSTRA.386#41]
This is one very awesome bootstrap theme. In fact, I am very sure where to use it; as a stats page for my server. Since it provides a terminal to ssh into the server, that is pretty much a well-fitting theme. 

Normally I work with Bootstrap 3. I am not sure how much the code has advanced in comparsion to the demo, but:

- Progress bars still seem to be using a gradient color. Not sure but it looked that way.
- Some of the buttons are glitched. Like the button with loading state looses its shadow and shrinks down, then back up when it changes back again.
- The button sizes seem a bit odd. The small an dmini button are almost similar.
- There are no distinct colours for Alert, Success, ...
- The brand part of the navbars are not having a background image.
- Primary navbar should be gray with black text, whilst inverse navbar should be black with white text.
- Modals arent styled at all, currently.
- Clicking a button makes it loose its shadow, therefore shrink and cause a flash o the interface.
- List styles don't have any indicator. Suggestion: draw a block that looks similar to a bigger pixel.
- In the search example, button and text field are not aligned. That will become problematic for my use case...
- The add-on buttons arent fitting correctly
- The dropdown buttons at the tabs example seem broken but I am not sure if they really are.
- Make `.well` have a border and look like a tiny window, after all, that seems to be what they technically are. At least, a little box with a shadow.

If I knew proper LESS and how to work the bootstrap theme, i would immedialy sit down and work these errors out. This theme is too cool to be true! :)

Kind regards, Ingwie

**Comment by kristopolous** [comment]
thanks i'll look into these.

**Comment by IngwiePhoenix** [comment]
Awesome! :)

**Comment by seiyria** [comment]
Any updates on this? I'm not keen on going back to bootstrap 2 just for this theme.

**Comment by kristopolous** [comment]
it should be fine ... just do it

**Comment by kristopolous** [comment]
oh wait this ticket

**Comment by kristopolous** [comment]
lol ok sure ... I was looking for stuff to do today

**Comment by kristopolous** [comment]
there we go ... step1 in the put 'em out, knock 'em down sophisticated advanced style of project management is done.

**Comment by kristopolous** [comment]
@IngwiePhoenix  look at https://github.com/kristopolous/BOOTSTRA.386/issues/47 I don't know if you'll get a notification on that one

**Comment by kristopolous** [comment]
@IngwiePhoenix also see #53, thanks

**Comment by seiyria** [comment]
@IngwiePhoenix You can also check this out: https://github.com/seiyria/dos-strap -- threw this together in a few hours for bootstrap 3. It's not got any animations or anything special built in, but it covers most of the visual aspects.

**Comment by IngwiePhoenix** [comment]
Hey!

So, so so so sorry @seiyria that I basically disappeared for so long. I once woke only to see all the notifications, since I watch the repo, and decided to work them down when i have time. I sat in the train and looked at them today, but im going to get into the swing with this theme and test a variety of things to prototype the desired project.

Again, very sorry for being so late on the topic. :)

**Comment by seiyria** [comment]
That's okay. I needed this particular thing soon so I threw my own together. Enjoy!

**Comment by kristopolous** [comment]
all these things have been addressed or separate bugs have been created so I'm closing this.
