### ISSUE TITLE
Progress bars still seem to be using a gradient color. Not sure but it looked that way.

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#43]
This is a breakout from #41

**Comment by kristopolous** [comment]
I disagree.  See here: https://www.diigo.com/item/image/5enzo/m9t8

Re-open if you contest this.

**Comment by IngwiePhoenix** [comment]
Could've been my eyes. I am partially sighted - thanks for looking.
Just in case, this also applies for the BS3 section/part?
