### ISSUE TITLE
The button sizes seem a bit odd. The small an dmini button are almost similar.

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#45]
Breakout from #41

**Comment by kristopolous** [comment]
correct ... I should probably use the first style as documented in #44 ... let's keep this open

**Comment by kristopolous** [comment]
So here's our starting point
![button-sizes](https://cloud.githubusercontent.com/assets/231761/10125920/e24c3f5c-6539-11e5-80eb-961ba51e013c.png)

... I can't really invent new things that weren't seen in the wild.   I'll have to do a bit more research to see what kind of plan I'd like to do.

the 2.x branch did exactly what we have here and didn't differentiate at all really.

**Comment by kristopolous** [comment]
so there's a 2d flat style ... 
![flat style](http://www.computerhope.com/jargon/e/doseditwindow.jpg)

The 3d button without any indicator:
![3d no indicator](http://www.bttr-software.de/forum/img/uploaded/image35.png)

Some really crazy thing in dos visual basic, which IMHO, I've never seen in the wild:
![VB](http://www.blogcdn.com/www.engadget.com/media/2008/06/vb-dos-1.jpg)

You also have decorated 3d buttons, which usually only happen when they are the actively selected one in an interface:
![active button](http://www.compu-seite.de/bilder/dos62/defrag.gif)

**Comment by kristopolous** [comment]
it's worth noting that the last one is breaking a lot of rules with regard to background colors ... it's a pretty late app

**Comment by kristopolous** [comment]
I'm still far from lovin' it but this is a slight improvement
![button-redesign](https://cloud.githubusercontent.com/assets/231761/10126055/1c736878-653e-11e5-961b-e62366303316.png)

**Comment by IngwiePhoenix** [comment]
I see. Well they did seem different at first glance - between 2.x and 3.x that is - but i might have been wrong.

But the last picture you posted makes things more distinct - I like that. Good idea here. :)

**Comment by kristopolous** [comment]
in the 2.x branch I made the large buttons actually occupy an extra height ... I think I'll do that here
