### ISSUE TITLE
There are no distinct colours for Alert, Success, ...

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#46]
Breakout from #41

**Comment by kristopolous** [comment]
I think the proper issue here is that there's inconsistency ... the button colors seem to be ok, but text ones don't seem to be respected.

**Comment by kristopolous** [comment]
ok so we have
## list groups (https://www.diigo.com/item/image/5enzo/hbq5)
<img src='https://s3.amazonaws.com/diigo/thumbnail_550/9075690_288377362_19337134.jpg?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1443395328&Signature=6QZA%2Bpohm17nTy9aicUH6x136DE%3D'>

## panels (https://www.diigo.com/item/image/5enzo/04yp)
<img src='https://www.diigo.com/item/t/SNVcfjQUb9kD5H71b1r1fJ%2BALSEerdasboXebJXT9bUa4BE3k6%2BvsCeTubha%0Ap1RU%0A'>

## alerts (https://www.diigo.com/item/image/5enzo/0jto)
<img src='http://s3.amazonaws.com/diigo/9075690_288377617_19337149?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1443395452&Signature=juuHlqcgZYscCO%2FBaY0ub3BCCDM%3D'>

## labels (https://www.diigo.com/item/image/5enzo/qkdh)
<img src='https://s3.amazonaws.com/diigo/thumbnail_550/9075690_288377947_19337173.jpg?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1443395673&Signature=CDIW5G4ug2kvLxucz9Nmtj%2Fg3r0%3D'>

## contextual backgrounds (https://www.diigo.com/item/image/5enzo/chij)
<img src='https://s3.amazonaws.com/diigo/thumbnail_550/9075690_288378098_19337177.jpg?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1443395796&Signature=L66Z92LXyjCx2hCvl3LWxG2T4Q4%3D'>

## buttons (https://www.diigo.com/item/image/5enzo/og0u)
<img src='https://s3.amazonaws.com/diigo/thumbnail_550/9075690_288378176_19337182.jpg?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1443395907&Signature=qr%2F2TSWtw%2Bm0N6ua5HWkHu0OI%2Bc%3D'>

If there's anything else I'm missing please re-open this

**Comment by IngwiePhoenix** [comment]
Nicely done! =)
