### ISSUE TITLE
The brand part of the navbars are not having a background image.

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#47]
Breakout from #41

**Comment by kristopolous** [comment]
can @IngwiePhoenix give me a code snippet here?

**Comment by IngwiePhoenix** [comment]
I thought I'd have seen it in the demo for BS3. But unfortunately, I seemingly am having problems to build the demo locally. The one online is Bs2.

Can you tell me what to run to build the local demo? I am not too familiar with Grunt, and `make build` didnt seem to do much either...

**Comment by kristopolous** [comment]
in one terminal type

jekyll serve

in another type

grunt watch

why they decided to do this I will never know.
