### ISSUE TITLE
Primary navbar should be gray with black text, whilst inverse navbar should be black with white text.

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#48]
Breakout from #41

**Comment by kristopolous** [comment]
it's a mixed bag ... it's certainly light grey background ... but sometimes it's blue text (as in qbasic) but in other things such as edit and word for dos, it's black on grey.

As far as the other one, I think that lotus123 is the inspiration: https://upload.wikimedia.org/wikipedia/en/e/ec/Lotus-123-3.0-dos.png which is the big one I can think of with this style.

Anyway, as you can see here: https://www.diigo.com/item/image/5enzo/ovda I'm observing both those styles (which coincidentally are the ones you suggested). So unless you contest this, I'm going to close it.

**Comment by IngwiePhoenix** [comment]
Nothing to add here, sounds solid and nice references.

I was a OS 9 kid, so I did not get to see much of the DOSyness. :)
