### ISSUE TITLE
Modal closes aren't styled

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#49]
Breakout from #41

**Comment by kristopolous** [comment]
The close button may need some work, but other than that I think this isn't a valid claim.  See here: https://www.diigo.com/item/image/5enzo/tn4b ... i'm going to rename this issue

**Comment by IngwiePhoenix** [comment]
Sometimes I wonder if I have seen an old version - because this one looks pretty awesome... o.o
