### ISSUE TITLE
List styles don't have any indicator. Suggestion: draw a block that looks similar to a bigger pixel.

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#51]
Breakout from #41

**Comment by kristopolous** [comment]
I believe this is already being done. See here: https://www.diigo.com/item/image/5enzo/c7r4 ... if you would like to contend this isn't what you are talking about then please re-open this bug.

**Comment by EvanCarroll** [comment]
@kristopolous see linked issue, I don't think that's what he's talking about.

**Comment by kristopolous** [comment]
For 2.0? alright. sure I'll look into it

**Comment by kristopolous** [comment]
Also this emphasizes out that I'll need to update the demo space and put the different versions there somewhere

**Comment by EvanCarroll** [comment]
@kristopolous  I'm not exactly sure what version. I'm using zula.386 which I believe is sourcing the real work from this project I would have to look into that. I just saw the issue already on the board, and see the issue is present in the demo.

**Comment by kristopolous** [comment]
zula.386? Did you spell that right? Can you link me to it?

**Comment by EvanCarroll** [comment]
No, I didn't spell it right. =( https://www.getzola.org/themes/zola-386/

Zola. The Rust static-content generator that competes with Hugo.

**Comment by kristopolous** [comment]
that is indeed v2. I just fixed it.

**Comment by kristopolous** [comment]
the disc list-style-type doesn't have an equivalent character in MS-ASCII but the square is basically character 254 so we'll just default to that.
![list](https://github.com/kristopolous/BOOTSTRA.386/assets/231761/eadab3d4-a0ac-4ce8-b3b0-992bafdc1fc4)

**Comment by kristopolous** [comment]
oh hey that alignment is wrong

**Comment by EvanCarroll** [comment]
This is a huge improvement, but why aren't ordered lists, numbered? I would expect that.

1. foo foo foo
2. bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar 
3. this is the third element

**Comment by kristopolous** [comment]
Why? Honestly because this is something I did for my own amusement 11 years ago.  But let's set that aside. Here you go.
Should be working.
![list](https://github.com/kristopolous/BOOTSTRA.386/assets/231761/a9a6e331-5c5e-4e27-99c6-7fc154b7220e)

**Comment by EvanCarroll** [comment]
That looks beautiful. As to why? Because this is Enterprise ready theming here. This shit is gold. Hell yes I'm going to use this. #BorlandIsBeautiful

**Comment by kristopolous** [comment]
cool, I hope you enjoyed my new japanese promo video on the project's main readme page over here: https://github.com/kristopolous/BOOTSTRA.386

**Comment by EvanCarroll** [comment]
Hahha that's glorious. Well done @kristopolous! Btw, if you like this Kitty has a Borland theme which compliments it well.
