### ISSUE TITLE
Make .well have a border and look like a tiny window, after all, that seems to be what they technically are. At least, a little box with a shadow.

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#55]
Breakout from #41

**Comment by kristopolous** [comment]
I do like the 2.x variation of the well more than the 3x.  So I think I'll do some work and just get the 2x to come over.

**Comment by IngwiePhoenix** [comment]
Sounds good to me. Go ahead! :)

**Comment by kristopolous** [comment]
ok great ... it matches
