### ISSUE TITLE
Issues with Carousel

### ISSUE THREAD

**Issue by turqoisehex** [kristopolous/BOOTSTRA.386#60]
On the javascript page, the buttons on the carousel don't consistently work. When clicking back and forth, sometimes they work, sometimes they don't. The selector in the top right also doesn't display correctly; when it's on the first image it shows none selected, on the second image it's invisible because of lack of contrast (white on white) and on the third image it shows the highlight on the first circle.

Tested on Chromium on Linux Mint, Windows 7, and Android.

Looking at the CSS, I wonder if it could be a mismatch issue; bootstrap.js shows version 3.3.2, while bootstrap.css shows version 2.3.1. I mirrored the demo locally and merged the carousel from bootstrap.css 3.3.7 into the BOOTSTRA.386 bootstrap.css and this fixed the functionality (while losing the great aesthetic). It didn't help with the slide selector being invisible when there's no contrast, but it slides and transitions correctly, and the controls work as expected.

I also can't seem to constrain the size of the carousel correctly (can't stop it from taking up the whole width and being aligned left) but this is probably just a result of my own inexperience.

I'll take this moment to thank you for creating the greatest bootstrap theme I've ever seen. I'm a novice with bootstrap, but I'll see if I'm capable of fixing the functionality without breaking the aesthetic. If I succeed I'll report back.

PS (unrelated) for people who don't want images super high contrast, it's at line 648 in bootstrap.css

EDIT:
It looks like merging in the transitions at line 5700 is what fixes it:
```
@media all and (transform-3d), (-webkit-transform-3d) {
  .carousel-inner > .item {
    -webkit-transition: -webkit-transform .01s ease-in-out;
         -o-transition:      -o-transform .01s ease-in-out;
            transition:         transform .01s ease-in-out;

    -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
    -webkit-perspective: 1000px;
            perspective: 1000px;
  }
  .carousel-inner > .item.next,
  .carousel-inner > .item.active.right {
    left: 0;
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
  }
  .carousel-inner > .item.prev,
  .carousel-inner > .item.active.left {
    left: 0;
    -webkit-transform: translate3d(-100%, 0, 0);
            transform: translate3d(-100%, 0, 0);
  }
  .carousel-inner > .item.next.left,
  .carousel-inner > .item.prev.right,
  .carousel-inner > .item.active {
    left: 0;
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
}
```
I changed the transition from default .6 to .01, which makes it not really a transition, but does fix the issues mentioned.

**Comment by novalic** [comment]
Hey buddy, I couldn't find the correct line to disable the high-contrast images. Line 648 in bootstrap.css refers to a glyphicon content. I downloaded the files at least 6 months after your post so file must have changed. Can you tell what is the code that makes the images on high contrast?
Ty!

**Comment by kristopolous** [comment]
the high-contrast was an effort to emulate ega-16 ... for some reason I'm not getting notices of these bugs. I don't have time to look into this right now but now I see there's lots of activity here I haven't attended to ... sorry
