### ISSUE TITLE
BS4 version

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#65]
Yet another round of BS has come out and I should probably support this BS because everyone else is working with and implementing all this BS. So let the BS work begin!

**Comment by Hectate** [comment]
I just happened to find this BS and it's great. Is a v4 being worked on? :)

**Comment by kristopolous** [comment]
yes, 2.5 years later, as the world collapses, I am dedicated to BS

**Comment by kristopolous** [comment]
Progress on the jumbotrons.

It takes the h1 text and then pushes it up to be a fake title. 

![jumbotron](https://user-images.githubusercontent.com/231761/80952055-e63f7b00-8dad-11ea-868a-009763f79e25.png)

**Comment by kristopolous** [comment]
style subject to change of course but there's been a good amount of new css since I wrote the first one in 2013/2014 ... a number of things are possible now that weren't then.

**Comment by kristopolous** [comment]
I was using the dialogs of qbasic here as a reference
![Qbasic_1](https://user-images.githubusercontent.com/231761/80957942-0294e500-8db9-11ea-83b3-668432fb70b6.png)

And this one is nice too. Centering is really really hard because it needs to follow the fictitious pixel grid and well, everything is fluid these days.

I'm not saying it's impossible, of course JavaScript can do magic, I'm just saying I haven't figured out a css only method that works extremely well and looks right yet
![nc-configuration-3](https://user-images.githubusercontent.com/231761/80958117-58698d00-8db9-11ea-8231-d70a2da98a53.png)

**Comment by kristopolous** [comment]
I'm going to get a status page going soon ...

**Comment by kristopolous** [comment]
http://kristopolous.github.io/BOOTSTRA.386/demo.html it's still pretty fucked up but yeah ... the first version took like 6 months.

**Comment by kristopolous** [comment]
I'm going to make about 20 of these at the end of the month, load them with version 2/3/4, maybe some little surprises  or so, and put them on ebay for $5 each. I'll update the readme and tell y'all when it's there.

Buy my software, yo!

![bootstra](https://user-images.githubusercontent.com/231761/82211504-cc318c80-98c5-11ea-8dc3-b28e4e359135.jpg)

**Comment by spotUP** [comment]
So... v4 will gout out of wip state by the end of the month? <3

**Comment by kristopolous** [comment]
That's the current plan. We'll see how close I hit it.
![text-area](https://user-images.githubusercontent.com/231761/82614304-602c7e00-9b7c-11ea-8ab2-067794380458.png)

**Comment by kristopolous** [comment]
when I get it perfect it messes with my brain, because it enters this mysterious UX uncanny valley. It's pretty surreal, unlike anything I've experienced before.

**Comment by spotUP** [comment]
Awesome =)

**Comment by kristopolous** [comment]
so end of the month is getting close I'll make a milestone with the bugs

**Comment by kristopolous** [comment]
Alright things have been itemized in #85 ...
