### ISSUE TITLE
Current BS 3.3.2 dist broken

### ISSUE THREAD

**Issue by ypnos-web** [kristopolous/BOOTSTRA.386#66]
Hi,

this is really the greatest BS I have seen so far. However your current release is broken for older BS:

1. Font files are expected in css/fonts but missing. Can be copied over from 2.3.1
2. `bootstrap.js` includes:
```
/**
* IMPORTS
*/
var color_diff    = require('./diff');
var color_convert = require('./convert');
…
// Local Variables:
// allout-layout: t
// js-indent-level: 2
// End:

var convert = require('./convert');
var palette = require('./palette');
```

Apart from `require()` not working, I also did not find any of these files.

**Comment by jtiscione** [comment]
A bunch of files seem to be missing. Nothing looks like it does in the demo.

**Comment by kristopolous** [comment]
hrmm that sucks ... let me try
