### ISSUE TITLE
provide a bootstrap 3 version - please :D

### ISSUE THREAD

**Issue by kaystrobach** [kristopolous/BOOTSTRA.386#7]

**Comment by ddo** [comment]
any update ?

**Comment by TehShrike** [comment]
I don't see a Bootstrap 3 branch, is there a fork anywhere that people are working on?

**Comment by kristopolous** [comment]
I have a large number of aborted attempts.

The problem is that the new stack with npm, composer, grunt, transpilers and all rest has made development really really unbelievably hard and extraordinarily complex.

I've spent dozens of hours with all these bizarre hipster stacks they are using now and am getting nowhere.

**Comment by TehShrike** [comment]
ah, that sucks!

**Comment by kristopolous** [comment]
yeah I know there's a large demand for this ... it's just be so discouraging spinning my wheels on it

**Comment by snipe** [comment]
Would you mind if I took a stab at this? At least getting the basic scaffolding up?

**Comment by snipe** [comment]
You don't actually need npm, grunt, etc to build the theme. That stuff just takes care of downloading all of the files and dependencies, and compiling SASS files and such. 

You should probably use SASS, in which case grunt (or if you're on a Mac, something like SiteFlow) is helpful, since it watches the sass files and then generates a CSS file from it, but I think you can make this ready for Bootstrap 3 without most of the hipster crap. You shouldn't be touching the actual `bootstrap.css` anyway, but instead using an theme override file, so I think you may be over-complicating what's necessary. I'm happy to fork it and take a stab though.

**Comment by kristopolous** [comment]
@snipe hit me up on skype/aim/facebook/google/yahoo using the handle kristopolous ... thanks

**Comment by kristopolous** [comment]
ok i'm finally starting it.

**Comment by kristopolous** [comment]
ok so I won't be updating this ticket too often.  Thanks to @snipe for the encouragement ... I can get overwhelmed by unneeded complexities sometime (kinda silly since I've been doing this stuff for 20 years).  Anyway, the v3 is going through some rapid revisions now so I guess just follow master to stay in the loop.  

It will take the order of probably a few weeks - css as you know, is often hard and exhausting.

**Comment by peter-mw** [comment]
when? pls make it sooner!

**Comment by snipe** [comment]
@peter-mw It's never wise to pester people who are giving you free software. @kristopolous said a few weeks. It's a big job and he's allowed to have some semblance of a life, too. :)

**Comment by kristopolous** [comment]
Hi @peter-mw, it's currently under constant development and is converging to where I'd like it to be. 

Things like proper grid spacing are really the most time consuming. You are free to check it out any time and follow the progress.

I'd love your feedback.

Thanks!

**Comment by peter-mw** [comment]
@snipe @kristopolous cool :) i didnt mean to push you just was too excited, whenever its ready i will use it. take your time and keep calm :)

**Comment by snipe** [comment]
![tumblr_inline_nk9fi0yqif1r79k32](https://cloud.githubusercontent.com/assets/197404/6517383/45ff5d64-c34f-11e4-89e5-413aca6487f0.gif)

:D

**Comment by peter-mw** [comment]
BOOTSTRA.386 for Bootstrap3 will be mind blowing :D 

![dyo6x](https://cloud.githubusercontent.com/assets/5698247/6518110/21f223dc-c3ab-11e4-81c9-e567d97499a2.gif)

**Comment by kristopolous** [comment]
ok if we are playing that game then I'll employ my https://github.com/kristopolous/UniFig project for making variable-width unicode art ... 

▄░▄▄▄░▄░▄▄▄▄░░░░▄▄▄▄░▄▄▄▄░▄░░▄░▄░▄░░▄░▄▄▄▄ 
▓░░▓░░▓░▓▄▄░░░░░▓░░░░▓░░▓░▓█▓▓░▓░▓█░▓░▓░▄▄ 
▓░░▓░░░░▄▄▄▌░░░░▓▄▄▄░▓▄▄▌░▓░░▓░▓░▓░█▓░▓▄▄▌

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄▀▌  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄▄▀▀▓▀░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄▄▀▓▀░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄▀▀▓▀░░▌░░░░░░▄░░░░░░▌  ░░░░░░░░░░░░░░░░░░░░░░░▄▄▄▄░░░░░░░░░░▄▄▄▀▐█░░░░░░▌░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░▄▄▄▀▀▀░░▀▀▀▄▄▄▄▄▀▀░░░░░█▄░░░░░░▌░░░░░░░░░░░░░▌  ░░░░░░░░░░░░░▄▄▄▀▀▀░▌▌▀░░▀▌░░░░▓░░░░░░░▄▄▀▄▌░░░░░░░▌░░░░▀░░░░░░░░  ░░░░░░░░░░░░█▀▄░░░░▄░░░░░░░█░░▓░░░░░░▄▀░░▄░░▌░░▀░░░░▌░░░░░░░░░░░▌  ░░░░░░░░░░░░█▄▀▄░░░▀░░░░▄░░░█▄░█░░░░░█░░▄░░▌░░▄░░░░░▌░░░░▀░░░░░░░  ░░░░░░░░░░░░░░█▄▄▀▀▀▀▄▀▀░░░▀▓░░░█░░░░▓░▄░░▌░░░░░░░░░▌░░░░░░░░░▌░░  ░░░░░░░░░░░░░▄▄▀░░░░░░░▄▄▀░▓░░░░▓░░░░▓░▄░▌░░░░░▀░░░▌░░░░▀░░░░░░░░  ░░░░░░░░░░░░▓░░░░░░░░░░░░░▓░░░░▓░░░░▓░▀░▌░░░░░░░░░▌░░░░░░░░▌░░░░░  ░░░░░▄▀▀▀▄░▓░░░░░░░░░░░░░░▄▄▄▄▓░░░▄▀░░▌░░░░░░░░░░▌░░░░░▌░░░░░░░░░  ░░░░▓░░░░░█░░░░░░░░░░░░░░░▀▀▀▀░░░▓░░▌░░░░░░░░░░▌░░░▌░░░░░░░░░░░░░  ░░▄▀░▄██░░░█░░░░░░░░░░░░░░░░░░░▄▀░░▌░░░░▌░░░▌░░░░▄▀▀▀▀▀▀▄░░░░░░░░  █▀░░▓░░░█░░░▀▀░░░░░░░░░░░░░░▄▀▀░░▌░░░▌░░░▌▄░░░░▄▀░░░░░░░░▐█░░░░░░  ▓░░░▌░░▓░█░░░░░░░░░░░░░░▄▄▄▀░░░▌░░▌░▄▄▌▀░░░▀▀▄▀░░░░░░░░░░░░█░░░░░  ░█░▓░█░▌█░█░░░░░░░░░░░░░▐█░░░▌▄▄▄▀▄▀░░░░░░░░░░░░░▄▄▀█▀█░░░░▓░░░░░  ░░▀▀▄▓░█▄█░█▄▄▄▄▄░░░░░░░░░▀▄▀░░░░░░░░░░░░░░░░░░▌▓░░░░▄▓░░░░▓░░░░░  ░░░░█░░░▓██░▀▀▀░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█░▄▄▀░░░░░▓░░░░░░  ░░░░░▐█▄▓▄▌░▀▀▄▀▀▀▀▀▄░░░░░░░░░░░░░▀▀▀▄▄░░░░░░░░░░█░░▄▄▄▄▄▀░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░▀▀▀▄▄▄▄▄░░▄▄▄▄▀▀▀░█░░░░░░░░░█░█▄▄▄▀▓░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄▐█▄░░░░░░▄▄▌▄▄░░░░░░░▀▀▄▄▀▓░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░▌░░░░░▀▀▄▄░░░█░░░▀▀▀▄▄░░░░░▀▓░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░▌░▄▌▀▀▄░░░░░░░█░░░░░░░▀▀▀▄░░░█░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░█▀░▓░░░▀▀▄▄░░▄▀░░░░░░░░░░░▐█░░█░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█░░░▓▀▀▀▄░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█▄▄▄█▄▄░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

**Comment by kristopolous** [comment]
It's coming along nicely, anyone want to help me beta test it?

**Comment by peter-mw** [comment]
i can try it on my site on the weekend

**Comment by alexsupra** [comment]
i can try it on my web site on this weekend too

On Thu, Mar 12, 2015 at 4:47 PM, Peter Ivanov <notifications@github.com>
wrote:

> i can try it on my site on the weekend
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kristopolous/BOOTSTRA.386/issues/7#issuecomment-78482083>
> .
>



-- 
alex

**Comment by seriema** [comment]
Me too (even if my site is extremely basic)

**Comment by kristopolous** [comment]
ok sure ... so here's how it will roll ... look at https://github.com/kristopolous/BOOTSTRA.386/blob/master/CONTRIBUTING.md to see what I consider to be a bug and what would be most useful for me.

I've registered ##bootstra386 on freenode.  I'll try to be on it the next few days and so you can catch me there.  Also you can hit me up on skype or other chat networks with the handle kristopolous.

I'm going to tag a beta tomorrow afternoon ... please do your bug reports from that tag until I update.

If you want to call or text me, factor 57015009877788133 for my phone number.  Thanks.

**Comment by kristopolous** [comment]
The tag is https://github.com/kristopolous/BOOTSTRA.386/tree/bs3-pre1 ... have fun.

**Comment by kristopolous** [comment]
so how goes it? anyone try it?

**Comment by peter-mw** [comment]
I started making a template, but still not ready

**Comment by snipe** [comment]
I'm hoping to work on the Wordpress template this week

**Comment by nemoo** [comment]
I tried it briefly on a little bootstrap 3 project of mine and it works great out of the box!

**Comment by kristopolous** [comment]
great ... my main concern is that although i was pretty faithful to my rules I don't think this version is aesthetically sufficient.  

Aesthetic balance was one aspect I really hit home on with the v2 -- probably because the v2 landing page was essentially 100% bootstrap css (something they decided not to do with v3).  So I had a lot of sample content to work with.

My primary interest now is that the style will look "right" in the wild on real sites ... so as you test this, if you can *share* your projects with me so I can use them as my sample data set to get this aspect right it would be most appreciated.

Thanks for all your support and I look forward to seeing what you create.

**Comment by seriema** [comment]
I tried it just now and getting some alignment issues in the footer (.inline-list) and links inside panels have the same color as the background.
Dump: https://dl.dropboxusercontent.com/u/5566693/index.html

Original:
My website: http://johansson.jp/
Github: https://github.com/seriema/seriema.github.io/

**Comment by kristopolous** [comment]
hey hey, thanks! I was just about to call this a release.  Glad you came forward. Let me look into it.

**Comment by kristopolous** [comment]
@seriema is the github the source code for this minified site?  I can't really debug it in its current form.

**Comment by seriema** [comment]
Yepp. I just didn't commit the BOOTSTRA.386 
You can probably take the unminified HTML and just add your CSS to it. It's a very simple site. =)

**Comment by kristopolous** [comment]
ok I think I fixed the errors that were showing up on your site ... please check it out again. Thanks

**Comment by kristopolous** [comment]
ok I'm going to assume these are patched.

**Comment by kristopolous** [comment]
If you didn't notice, I tagged a pre2.  This is intended to be my last before a release. So please do your testing!

**Comment by fastofruto** [comment]
Hi, just want to know how is v3 going.
When will the final release done?
Thanks!

**Comment by seriema** [comment]
Sorry for never replying. I did a new test, using your pre2 version, which you can see [here](https://dl.dropboxusercontent.com/u/5566693/bootstra386/index.html). Don't worry about the overlapping texts below the icons, I was hiding it with custom CSS (which I disabled for now). You can compare to it using Bootstrap 3.3.5 [here](https://dl.dropboxusercontent.com/u/5566693/bootstrap335/index.html). I'm not using the `.theme.css` on either.

`.lead { line-height: 1; }` seems a bit tight.
`.list-inline` is missing a `margin-left: -10px;` or similar to compensate for the padding that the `li` elements are adding. (my footer again)

**Comment by kristopolous** [comment]
@fastofruto use it and find some problems.  I don't see many on my end ... @seriema thanks, I'll look into it.

**Comment by kristopolous** [comment]
### It's done now 
![party](http://images-pictures.org/wp-content/uploads/2015/05/birthday-party-clip-art-1.jpg)

**Comment by NurdTurd** [comment]
:dart: :+1:
