### ISSUE TITLE
I made a bootstrap v4 theme of this.

### ISSUE THREAD

**Issue by dessalines** [kristopolous/BOOTSTRA.386#74]
Very rudimentary, really only the colors and some other things, but here it is: 

https://github.com/dessalines/lemmy/blob/3f561710ef63fbb538abfbbbe8de7dbb3c361a14/ui/assets/css/themes/_variables.i386.scss

You can tweak it by importing it to https://bootstrap.build/ if you like.

**Comment by kristopolous** [comment]
right I need to do that. let me look

**Comment by dessalines** [comment]
I'll close this and let it go to the other ticket.
