### ISSUE TITLE
Problems with modals

### ISSUE THREAD

**Issue by spotUP** [kristopolous/BOOTSTRA.386#84]
Hi! I am building a site with the wip bootstrap 4 version.
I just wanted to let you know that there seems to be an issue with modals. No buttons can be clicked and the modal itself gets darkened as well.

**Comment by spotUP** [comment]
Lowering the z-index here fixes it:

.modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1029;
    width: 100vw;
    height: 100vh;
    background-color: #000;
}

**Comment by kristopolous** [comment]
Yep, modals aren't done yet. I'll get to them. Thanks.

**Comment by spotUP** [comment]
I see. My temp solution works for now.

**Comment by kristopolous** [comment]
they're working now, closing. thanks for the report
