### ISSUE TITLE
Menu doesn't colapse into a hamburger on mobile

### ISSUE THREAD

**Issue by spotUP** [kristopolous/BOOTSTRA.386#89]
I tried with a bootstrap example that should colapse into a hamburger as well but no go.

**Comment by spotUP** [comment]
whe're ya at dude?

**Comment by kristopolous** [comment]
Depression's a bitch. let me look into it.

**Comment by spotUP** [comment]
Oh.. I hope you feel better now!

**Comment by spotUP** [comment]
Any news? How are you?

**Comment by kristopolous** [comment]
Just sold my company (I think). Took 6 months. I'm getting back on this. I'm making a propaganda page http://9ol.es/bootstra/ (themed to look like the web from 1993/1994) and will fix these bugs up, get a demo ready, buy a domain, make some actual floppies, and do this for real.

**Comment by kristopolous** [comment]
ok, http://bootstra386.com/ ... there we go

**Comment by kristopolous** [comment]
I also created this crazy tool to browse apache directory listings (like http://aries.ucsd.edu/ICONS/AICONS/Buttons/ for instance) into an image gallery "http://9ol.es/apache-img.php?u=http://aries.ucsd.edu/ICONS/AICONS/Buttons/" ... this is so I can search "Index of" and "apache" and say "email2.gif" and [get some nice vintage results](https://www.google.com/search?q=%22Index+of%22+%22apache%22+%22email2.gif%22)

**Comment by spotUP** [comment]
The hamburger menu still doesn't work as intended on your demo site though?

**Comment by spotUP** [comment]
I got it working on my site now, it was a few missing css classes that caused it.

**Comment by dag7dev** [comment]
> I got it working on my site now, it was a few missing css classes that caused it.
@spotUP 
So you managed to get it working?

**Comment by spotUP** [comment]
No issues, use the developer tools and you can see what classes it wants.
