### ISSUE TITLE
[bs2] mobile menu bar doesn't generate right

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/BOOTSTRA.386#9]
on the demo page. the mobile menu is screwed up.

**Comment by DannyCork** [comment]
sure is :(

**Comment by kristopolous** [comment]
oh man, a frownie face ... I must address this immediately!  Do you still really care about bs2?

**Comment by kristopolous** [comment]
I'm citing JWZ's famous CADT here: https://www.jwz.org/doc/cadt.html ... on to BS 4.
