### ISSUE TITLE
How can I use this with Jekyll?

### ISSUE THREAD

**Issue by daemonspudguy** [kristopolous/BOOTSTRA.386#92]
I feel like an idiot for asking this, but how can I use this with my Jekyll site?

**Comment by kristopolous** [comment]
oh you aren't. I'm the idiot here for not knowing what jekyll is. Can you link me so I can see?

**Comment by daemonspudguy** [comment]
https://jekyllrb.com

**Comment by daemonspudguy** [comment]
@kristopolous I have since switched to hugo for my site which has a direct port of this theme.
