### ISSUE TITLE
Text - Weird check boxes?

### ISSUE THREAD

**Issue by Visual917** [kristopolous/BOOTSTRA.386#97]
![image](https://user-images.githubusercontent.com/30579752/109342633-30ce3e80-787d-11eb-82de-ae0834e40db0.png)

I have two text objects on the page. "Help Text" to be exact since I am using the theme with Bootstrap Studio. When I start the preview for the page, these show and become invisible two seconds after. How to fix this?

**Comment by kristopolous** [comment]
Can you give me the version or html for this?

**Comment by Visual917** [comment]
> Can you give me the version or html for this?

Oh my. Hi. It has been 2.5 years. I am not super invested in that project anymore. If you're developing the new version, I'll use that in the future but right now I'll just use NextJS.
