### ISSUE TITLE
Underwhelming tables

### ISSUE THREAD

**Issue by spotUP** [kristopolous/BOOTSTRA.386#98]
Hi! The tables are a bit underwhelming compared to the bootsrap tables, missing pagination, sorting, search etc.
Could that be added?

**Comment by spotUP** [comment]
search and pagination can be added but sorting would be dope.

**Comment by cognivore** [comment]
I think it would help if you would suggest a DOS-based design for these.

**Comment by kristopolous** [comment]
I don't think the UI paradigms that we employ these days were around in the CLI days.

I guess you could argue for a variety of tabular styles but I think when those things existed they were mostly done through the F-key row back in the day as opposed to a pointing device, which is the preferred way now. 

I guess what you could do is show an F-key menu and then the user can click on the English words to do the table operations.

**Comment by kristopolous** [comment]
Actually I have to agree ... these tables are fucked. I'm working on it.

**Comment by kristopolous** [comment]
Here's our fix.
![tables](https://github.com/kristopolous/BOOTSTRA.386/assets/231761/34178cab-b226-4e83-ab7c-0404a85449de)

**Comment by kristopolous** [comment]
reopen if you want more.
